name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      fail-fast: false

    steps:
      - name: Checking out
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Tree README
        uses: RavelloH/readme-tree@v1.1.0
        with:
          showsize: "no"

      - name: commit
        continue-on-error: True
        run: |
          git init
          git pull
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "[Readme-Tree]`date '+%Y-%m-%d %H:%M:%S'`" || exit
          git status
          git push -f
